# Python's operators on arrays and ints. The frontend desugars x @ w to
# operator.matmul(x, w), x + y to operator.add(x, y), -x to operator.neg(x),
# and so on. A float is a 0-d array, so it broadcasts with anything.

from typing import overload

from jaxtyping import Shaped
from shapecheck.stubs import Dim
from torch import Tensor

# ---- arithmetic: arrays broadcast, ints compute ----

@overload
def add(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def add(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def add(a: int, b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*B"]: ...
@overload
def add(a: int, b: int) -> Dim["a+b"]: ...

@overload
def sub(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def sub(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def sub(a: int, b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*B"]: ...
@overload
def sub(a: int, b: int) -> Dim["a-b"]: ...

@overload
def mul(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def mul(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def mul(a: int, b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*B"]: ...
@overload
def mul(a: int, b: int) -> Dim["a*b"]: ...

@overload
def truediv(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def truediv(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def truediv(a: int, b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*B"]: ...
@overload
def truediv(a: int, b: int) -> float: ...

@overload
def floordiv(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def floordiv(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def floordiv(a: int, b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*B"]: ...
@overload
def floordiv(a: int, b: int) -> Dim["a//b"]: ...
# when b isn't provably positive, the quotient is some int
@overload
def floordiv(a: int, b: int) -> int: ...

@overload
def pow(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def pow(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def pow(a: int, b: int) -> int: ...

@overload
def neg(a: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
@overload
def neg(a: int) -> Dim["-a"]: ...

# ---- matmul: numpy's rules for 1-d and batched operands ----

@overload
def matmul(a: Shaped[Tensor, "n"], b: Shaped[Tensor, "n"]) -> Shaped[Tensor, ""]: ...
@overload
def matmul(a: Shaped[Tensor, "*A m n"], b: Shaped[Tensor, "n"]) -> Shaped[Tensor, "*A m"]: ...
@overload
def matmul(a: Shaped[Tensor, "n"], b: Shaped[Tensor, "*B n p"]) -> Shaped[Tensor, "*B p"]: ...
@overload
def matmul(a: Shaped[Tensor, "*A m n"], b: Shaped[Tensor, "*B n p"]) -> Shaped[Tensor, "*broadcast(A,B) m p"]: ...

# ---- comparisons: arrays give broadcast masks, ints give bools ----

@overload
def lt(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def lt(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def lt(a: int, b: int) -> bool: ...

@overload
def le(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def le(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def le(a: int, b: int) -> bool: ...

@overload
def gt(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def gt(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def gt(a: int, b: int) -> bool: ...

@overload
def ge(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def ge(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def ge(a: int, b: int) -> bool: ...

@overload
def eq(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def eq(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def eq(a: int, b: int) -> bool: ...

@overload
def ne(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def ne(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def ne(a: int, b: int) -> bool: ...

# ---- bitwise: masks broadcast, ints compute ----

@overload
def and_(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def and_(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def and_(a: int, b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*B"]: ...
@overload
def and_(a: int, b: int) -> int: ...

@overload
def or_(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def or_(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def or_(a: int, b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*B"]: ...
@overload
def or_(a: int, b: int) -> int: ...

@overload
def xor(a: Shaped[Tensor, "*A"], b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
@overload
def xor(a: Shaped[Tensor, "*A"], b: int) -> Shaped[Tensor, "*A"]: ...
@overload
def xor(a: int, b: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*B"]: ...
@overload
def xor(a: int, b: int) -> int: ...

@overload
def invert(a: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
@overload
def invert(a: int) -> Dim["-a-1"]: ...

# ---- slice assignment: x[a:b] = v writes into x, which keeps its shape ----
# the frontend passes the slice x[a:b] itself as target, not x and the key

@overload
def setitem(target: Shaped[Tensor, "*A"], value: Shaped[Tensor, "*#A"]) -> None: ...
@overload
def setitem(target: Shaped[Tensor, "*A"], value: int) -> None: ...
