# Shapes of the torch functions and Tensor methods the checker knows.
#
# Stubs use jaxtyping shape strings plus a few things jaxtyping can't say:
#   - a shape may name an int parameter, e.g. "*drop(A,dim)" for sum's dim
#   - list functions: *drop(A,i), *keep(A,i), *permute(A,i,j), *swap(A,i,j),
#     *setat(A,i,d), *insertat(A,i,d), *broadcast(A,B), and prod(A), rank(A),
#     A[i] (one dim) in arithmetic
#   - Dim["expr"] is an int equal to a dim expression
#   - Shape["*S"] is a tuple of ints used as a shape; *size: Shape["*S"]
#     collects int arguments, so zeros(n, d) and zeros((n, d)) both work. one
#     entry may be -1 when an equation the stub asserts determines it, as in
#     reshape
#   - asserts are preconditions, or postconditions when they mention a name
#     only the return type binds
# Overloads are tried in order; the first that checks is used.

from typing import Literal, overload

from jaxtyping import Shaped
from shapecheck.stubs import Dim, Shape

class Tensor:
    @property
    def T(self: Shaped[Tensor, "m n"]) -> Shaped[Tensor, "n m"]: ...
    @property
    def mT(self: Shaped[Tensor, "*A m n"]) -> Shaped[Tensor, "*A n m"]: ...
    @property
    def ndim(self: Shaped[Tensor, "*A"]) -> Dim["rank(A)"]: ...

    def dim(self: Shaped[Tensor, "*A"]) -> Dim["rank(A)"]: ...
    def size(self: Shaped[Tensor, "*A"], dim: int) -> Dim["A[dim]"]: ...
    def numel(self: Shaped[Tensor, "*A"]) -> Dim["prod(A)"]: ...

    # ---- same shape ----
    def abs(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def exp(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def log(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def sqrt(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def tanh(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def sigmoid(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def relu(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def clone(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def detach(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def contiguous(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def float(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
    def softmax(self: Shaped[Tensor, "*A"], dim: int) -> Shaped[Tensor, "*A"]: ...
    def log_softmax(self: Shaped[Tensor, "*A"], dim: int) -> Shaped[Tensor, "*A"]: ...
    def triu(self: Shaped[Tensor, "*A m n"], diagonal: int = 0) -> Shaped[Tensor, "*A m n"]: ...
    def tril(self: Shaped[Tensor, "*A m n"], diagonal: int = 0) -> Shaped[Tensor, "*A m n"]: ...

    # ---- reductions ----
    @overload
    def sum(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, ""]: ...
    @overload
    def sum(self: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[False] = False) -> Shaped[Tensor, "*drop(A,dim)"]: ...
    @overload
    def sum(self: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[True]) -> Shaped[Tensor, "*setat(A,dim,1)"]: ...
    @overload
    def mean(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, ""]: ...
    @overload
    def mean(self: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[False] = False) -> Shaped[Tensor, "*drop(A,dim)"]: ...
    @overload
    def mean(self: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[True]) -> Shaped[Tensor, "*setat(A,dim,1)"]: ...
    @overload
    def amax(self: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[False] = False) -> Shaped[Tensor, "*drop(A,dim)"]: ...
    @overload
    def amax(self: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[True]) -> Shaped[Tensor, "*setat(A,dim,1)"]: ...
    def argmax(self: Shaped[Tensor, "*A"], dim: int) -> Shaped[Tensor, "*drop(A,dim)"]: ...

    # ---- reshaping ----
    def reshape(self: Shaped[Tensor, "*A"], *shape: Shape["*B"]) -> Shaped[Tensor, "*B"]:
        assert prod(A) == prod(B)
    def view(self: Shaped[Tensor, "*A"], *shape: Shape["*B"]) -> Shaped[Tensor, "*B"]:
        assert prod(A) == prod(B)
    @overload
    def flatten(self: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "prod(A)"]: ...
    @overload
    def flatten(self: Shaped[Tensor, "b *A"], start_dim: Literal[1]) -> Shaped[Tensor, "b prod(A)"]: ...
    def unsqueeze(self: Shaped[Tensor, "*A"], dim: int) -> Shaped[Tensor, "*insertat(A,dim,1)"]: ...
    def transpose(self: Shaped[Tensor, "*A"], dim0: int, dim1: int) -> Shaped[Tensor, "*swap(A,dim0,dim1)"]: ...

    # ---- masking: the mask broadcasts to self ----
    def masked_fill(self: Shaped[Tensor, "*A"], mask: Shaped[Tensor, "*#A"], value: float) -> Shaped[Tensor, "*A"]: ...

    # ---- products ----
    @overload
    def matmul(self: Shaped[Tensor, "n"], other: Shaped[Tensor, "n"]) -> Shaped[Tensor, ""]: ...
    @overload
    def matmul(self: Shaped[Tensor, "*A m n"], other: Shaped[Tensor, "n"]) -> Shaped[Tensor, "*A m"]: ...
    @overload
    def matmul(self: Shaped[Tensor, "n"], other: Shaped[Tensor, "*B n p"]) -> Shaped[Tensor, "*B p"]: ...
    @overload
    def matmul(self: Shaped[Tensor, "*A m n"], other: Shaped[Tensor, "*B n p"]) -> Shaped[Tensor, "*broadcast(A,B) m p"]: ...

# ---- creation ----

def zeros(*size: Shape["*S"]) -> Shaped[Tensor, "*S"]: ...
def ones(*size: Shape["*S"]) -> Shaped[Tensor, "*S"]: ...
def empty(*size: Shape["*S"]) -> Shaped[Tensor, "*S"]: ...
def rand(*size: Shape["*S"]) -> Shaped[Tensor, "*S"]: ...
def randn(*size: Shape["*S"]) -> Shaped[Tensor, "*S"]: ...
def zeros_like(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def ones_like(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def randn_like(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
@overload
def arange(end: int) -> Shaped[Tensor, "end"]: ...
# torch rejects start > end for a positive step
@overload
def arange(start: int, end: int, step: int = 1) -> Shaped[Tensor, "(end-start+step-1)//step"]:
    assert start <= end and step >= 1

# ---- same shape ----

def abs(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def exp(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def log(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def sqrt(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def tanh(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def sigmoid(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def sin(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def cos(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def relu(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "*A"]: ...
def softmax(input: Shaped[Tensor, "*A"], dim: int) -> Shaped[Tensor, "*A"]: ...
def log_softmax(input: Shaped[Tensor, "*A"], dim: int) -> Shaped[Tensor, "*A"]: ...
def triu(input: Shaped[Tensor, "*A m n"], diagonal: int = 0) -> Shaped[Tensor, "*A m n"]: ...
def tril(input: Shaped[Tensor, "*A m n"], diagonal: int = 0) -> Shaped[Tensor, "*A m n"]: ...

# ---- broadcasting ----

def masked_fill(input: Shaped[Tensor, "*A"], mask: Shaped[Tensor, "*#A"], value: float) -> Shaped[Tensor, "*A"]: ...
def where(condition: Shaped[Tensor, "*A"], input: Shaped[Tensor, "*B"], other: Shaped[Tensor, "*C"]) -> Shaped[Tensor, "*broadcast(A,B,C)"]: ...
def maximum(input: Shaped[Tensor, "*A"], other: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...
def minimum(input: Shaped[Tensor, "*A"], other: Shaped[Tensor, "*B"]) -> Shaped[Tensor, "*broadcast(A,B)"]: ...

# ---- reductions ----

@overload
def sum(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, ""]: ...
@overload
def sum(input: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[False] = False) -> Shaped[Tensor, "*drop(A,dim)"]: ...
@overload
def sum(input: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[True]) -> Shaped[Tensor, "*setat(A,dim,1)"]: ...
@overload
def mean(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, ""]: ...
@overload
def mean(input: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[False] = False) -> Shaped[Tensor, "*drop(A,dim)"]: ...
@overload
def mean(input: Shaped[Tensor, "*A"], dim: int, keepdim: Literal[True]) -> Shaped[Tensor, "*setat(A,dim,1)"]: ...
def argmax(input: Shaped[Tensor, "*A"], dim: int) -> Shaped[Tensor, "*drop(A,dim)"]: ...

# ---- reshaping ----

def reshape(input: Shaped[Tensor, "*A"], shape: Shape["*B"]) -> Shaped[Tensor, "*B"]:
    assert prod(A) == prod(B)
@overload
def flatten(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "prod(A)"]: ...
@overload
def flatten(input: Shaped[Tensor, "b *A"], start_dim: Literal[1]) -> Shaped[Tensor, "b prod(A)"]: ...
def unsqueeze(input: Shaped[Tensor, "*A"], dim: int) -> Shaped[Tensor, "*insertat(A,dim,1)"]: ...
def transpose(input: Shaped[Tensor, "*A"], dim0: int, dim1: int) -> Shaped[Tensor, "*swap(A,dim0,dim1)"]: ...

# ---- products ----

@overload
def matmul(input: Shaped[Tensor, "n"], other: Shaped[Tensor, "n"]) -> Shaped[Tensor, ""]: ...
@overload
def matmul(input: Shaped[Tensor, "*A m n"], other: Shaped[Tensor, "n"]) -> Shaped[Tensor, "*A m"]: ...
@overload
def matmul(input: Shaped[Tensor, "n"], other: Shaped[Tensor, "*B n p"]) -> Shaped[Tensor, "*B p"]: ...
@overload
def matmul(input: Shaped[Tensor, "*A m n"], other: Shaped[Tensor, "*B n p"]) -> Shaped[Tensor, "*broadcast(A,B) m p"]: ...
def outer(input: Shaped[Tensor, "n"], vec2: Shaped[Tensor, "m"]) -> Shaped[Tensor, "n m"]: ...
def bmm(input: Shaped[Tensor, "b n m"], mat2: Shaped[Tensor, "b m p"]) -> Shaped[Tensor, "b n p"]: ...

# ---- data-dependent sizes ----

def unique(input: Shaped[Tensor, "n"]) -> Shaped[Tensor, "m"]:
    assert m <= n
def nonzero(input: Shaped[Tensor, "*A"]) -> Shaped[Tensor, "k rank(A)"]:
    assert k <= prod(A)
